name: Slimdown Windows 10

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # allows the workflow to be triggered manually

jobs:
  slimdown:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download ISO
      run: |
        Start-BitsTransfer -Source "https://isofiles.bd581e55.workers.dev/Windows%2010/Windows%2010%20Enterprise%20LTSC%202021/en-us_windows_10_iot_enterprise_ltsc_2021_x64_dvd_257ad90f.iso" -Destination "Windows10_x64_en-US.iso"
      shell: powershell
      working-directory: ${{ github.workspace }}
    - name: Run Slimdown10.bat
      run: |
        .\Slimdown10.bat
      shell: cmd
      working-directory: ${{ github.workspace }}
    - name: Upload ISO
      uses: actions/upload-artifact@v2
      with:
        name: Windows10_x64_en-US.iso
        path: Windows10_x64_en-US.iso
      working-directory: ${{ github.workspace }}
